### ISSUE TITLE
CSS style is not shown

### ISSUE THREAD

**Issue by guocheng** [jsdir/react-ladda#22]
I am using `react@0.14.3` and `react-ladda@4.0.0`. After I load the page, the ladda button does not have any styles associated with it.  Here is the code I used

```js
import LaddaButton from 'react-ladda'

//inside render

<LaddaButton loading={isSaving}
                        onClick={this.handleSubmit}
                        buttonStyle="slide-down" > 保存 </LaddaButton>
```

**Comment by jsdir** [comment]
You'll need to manually include the Ladda stylesheet from https://github.com/hakimel/Ladda
