### ISSUE TITLE
Update React peer dependency to v15.0

### ISSUE THREAD

**Issue by lancefisher** [jsdir/react-ladda#29]
React v15.0 is released, and is not compatible with the peer dependency listed since it is a major version bump.

**Comment by lancefisher** [comment]
See PR: https://github.com/jsdir/react-ladda/pull/28

**Comment by lancefisher** [comment]
Fixed with https://github.com/jsdir/react-ladda/pull/30

**Comment by jamalneufeld** [comment]
This needs to go along with a `react-ladda` patch version bump. As it stands npm isn't using the fix because it's still at `4.0.2`

**Comment by jsdir** [comment]
fixed in `react-ladda@4.0.3`

**Comment by lancefisher** [comment]
Thanks @jamalneufeld and @jsdir !
