### ISSUE TITLE
Ladda is not initialized if the component is mounted with loading = true

### ISSUE THREAD

**Issue by miladmostavi** [jsdir/react-ladda#32]
Hello,

I've noticed that if I render `<LaddaButton loading={true}` /> it won't show the spinner. However if I render it with false and then change it to true it shows correctly. Is this a ladda issue?

Thank you.

**Comment by Darmody** [comment]
I think this commit https://github.com/jsdir/react-ladda/commit/a48a20c08cf5a781335eb4a3b88f7f4851616cc5 had fixed this problem, could you check again with the latest version?
