### ISSUE TITLE
Warning: You are manually calling a React.PropTypes validation function for the `loading` prop on `LaddaButton`.

### ISSUE THREAD

**Issue by bitmapdata** [jsdir/react-ladda#36]
![screen shot 2016-08-27 at 8 51 29 am](https://cloud.githubusercontent.com/assets/3241312/18023363/72a597e6-6c33-11e6-9070-355e3538ea60.png)

**Comment by jsdir** [comment]
This is fixed in `react-ladda@5.0.0`.
