### ISSUE TITLE
Question:  Is there a way to display a custom message or <div> with 'CONTRACT_OVERLAY'

### ISSUE THREAD

**Issue by texaspacm** [jsdir/react-ladda#41]
Question (no issue)

My task could take 45-60 seconds.  I would like to display an overlay with a custom HTML Element.  

Similar to what Slack does when the page is loading the first time.

Is this possible?  

Thanks!

**Comment by jsdir** [comment]
This is more of a feature request for the Ladda library itself. `react-ladda` does not try to add extra functionality outside of the Ladda library. I would try asking on https://github.com/hakimel/Ladda
