### ISSUE TITLE
Upgrade to react 16

### ISSUE THREAD

**Issue by anhkhoi** [jsdir/react-ladda#53]
Current peerDependencies is:
`"peerDependencies": {
    "react": "^0.14.0 || ^15.0.0",
    "react-dom": "^0.14.0 || ^15.0.0"
  }
 `

It would be nice to update to version 16.

**Comment by jsdir** [comment]
Fixed in [`react-ladda@6.0.0`](https://github.com/jsdir/react-ladda/releases/tag/v6.0.0)
