### ISSUE TITLE
`data-color` prop accepts string color name, not hex value

### ISSUE THREAD

**Issue by cjmyles** [jsdir/react-ladda#57]
The docs state that `data-color` is a string hex value representing a color. However, this is contrary to [Ladda documentation:](https://github.com/hakimel/Ladda)

> data-color: green/red/blue/purple/mint

In testing, my string hex value was ignored, whereas "purple" had an impact. This is fine by me, I just think the documentation needs to be updated.

**Comment by jsdir** [comment]
Good catch. I pushed a fix for the documentation.
