### ISSUE TITLE
NPM still sees old React dependency

### ISSUE THREAD

**Issue by afrojas** [jsdir/react-ladda#8]
Howdy!

In the process of upgrading my project to React 0.13 I hit a peerDependecy issue with react-ladda. Checked out your source and your package.json does have 0.13.x. Then I checked the commit log.

NPM got 2.0.1 (8 days ago) before you fixed the dependency (2 days ago) and I think is cacheing that, even if you have pushed to NPM since then.

Methinks you just to bump the version, push to NPM, and we'd all be set.

Thanks for react-ladda, very useful!

**Comment by jsdir** [comment]
Thanks for reminding me. While I was thinking about how to document the compatibility change, I completely forgot to publish the new version.
